config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'ruby-on-rails-items', to: 'portfolios#ruby_on_rails'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto app-footer">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Renzo Scheffer</h3>
    <nav class="nav nav-masthead justify-content-center app-nav">
      <%= nav_helper "nav-link", "span" %>
      <%= login_helper "nav-link" %>
    </nav>
  </div>
</header>

app/views/shared/_blog_featured_blog.html.erb
<% if @featured_blog %>
  <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 font-italic"><%= @featured_blog.title %></h1>
      <p class="lead my-3"><%= @featured_blog.body.slice(0, 144) %> ...</p>
      <p class="lead mb-0"><%= link_to "Continue reading...", @featured_blog, class: "text-white" %></p>
    </div>
  </div>
<% end %>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<header class="blog-header py-3">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-4 pt-1">
      <%= link_to 'Write a new blog', new_blog_path, class: "text-muted" if logged_in?(:site_admin) %>
    </div>
    <div class="col-4 text-center">
      <a class="blog-header-logo text-dark" href="#">My Blog</a>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
      <%= login_helper "btn btn-sm btn-outline-secondary" %>
    </div>
  </div>
</header>

app/views/shared/_blog_nav.html.erb
<div class="nav-scroller py-1 mb-2">
  <nav class="nav d-flex justify-content-between">
    <%= nav_helper "p-2 text-muted", "span" %>
  </nav>
</div>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="#"><%= fa_icon "github" %></a></li>
      <li><a href="#"><%= fa_icon "facebook" %></a></li>
      <li><a href="#"><%= fa_icon "twitter" %></a></li>
      <li><a href="#"><%= fa_icon "instagram" %></a></li>
    </ol>
  </div>
</aside>

app/views/shared/_navigation.html.erb
<div class="<%= location %>">
  <%= nav_helper "", "span" %>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <% unless params[:id].nil? %>
        <%= link_to "View all portfolio items", portfolios_path %> /
      <% end %>
      <a href="#">Back to top</a>
    </p>
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">In diesen Blog schreibe ich, damit ich weniger Postkarten an die Familie
      verschicken muss ;). Aber natürlich versuche ich auch ein paar nützliche Tipps
      an andere Reisende weiter zu geben.</p>
    <p>
      <%= link_to "Find out more about me", about_me_path, class: "btn btn-primary" %>
      <%= link_to "My Blog", blogs_path, class: "btn btn-secondary" %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About Me</h4>
          <p class="text-muted">Hi, ich bin Renzo. Ich reise gerne um die Welt. Ich bin sportbegeistert
            (aktuelle Favoriten sind: Longboard fahren, Klettern, Kite-Skaten, Joggen).
            Motorrad fahre ich auch gerne.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper "text-white", "li" %>
            <li><%= login_helper "text-white" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark box-shadow">
    <div class="container d-flex justify-content-between">
      <%= link_to fa_icon("angellist") + "<strong>Renzel</strong>".html_safe, root_path, class: "navbar-brand d-flex align-items-center" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>